### ISSUE TITLE
Enhancement: Implement Gulzar vocabulary as a graph

### ISSUE THREAD

**Issue by pshirali** [sathishvj/gulzar#4]
There are some combinations of words which don't work well together. The vocabulary could be implemented as a DAG to make it more Gulzarish. The _type of oscillation_ will be chosen at random. The word for every subsequent section will be a random value from a subset that matches well with its preceding section, such that the shayari has optimum _wazan_.

Perhaps best implemented while sipping chai on a rainy day.

**Comment by sathishvj** [comment]
Not enough technology.  No mention of blockchain or AI either.
